---
repositories:
  - name: runix
    url: https://helm.runix.net

releases:
  - name: pgadmin
    namespace: pgadmin
    chart: runix/pgadmin4
    version: 1.59.0
    values:
      - values.yaml
    hooks:
      - events:
          - presync
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - vals eval -f manifests/secret.yaml | kubectl apply -f -
      - events:
          - postuninstall
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - vals eval -f manifests/secret.yaml | kubectl delete -f -
