repositories:
  - name: jetstack
    url: https://charts.jetstack.io
releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.19.1
    createNamespace: true
    values:
      - installCRDs: true
        prometheus:
          enabled: false
