apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opencode.fullname" . }}-workdir
  labels:
    {{- include "opencode.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.workdir.accessMode | quote }}
  storageClassName: {{ .Values.persistence.workdir.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.workdir.size | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opencode.fullname" . }}-worktree
  labels:
    {{- include "opencode.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.worktree.accessMode | quote }}
  storageClassName: {{ .Values.persistence.worktree.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.worktree.size | quote }}
