apiVersion: v1
kind: Service
metadata:
  name: {{ include "nut-exporter.fullname" . }}
  labels:
    {{- include "nut-exporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "nut-exporter.selectorLabels" . | nindent 4 }}
