---
image:
  repository: ghcr.io/esanchezm/prometheus-qbittorrent-exporter
  tag: v1.6.0

qbittorrent:
  host: qbittorrent-vpn.qbittorrent-vpn.svc.cluster.local
  port: 8080
  username: ref+envsubst://$QBITTORRENT_WEBUI_USERNAME
  password: ref+envsubst://$QBITTORRENT_WEBUI_PASSWORD

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  release: monitoring

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
