---
architecture: standalone

auth:
  enabled: false

master:
  persistence:
    enabled: true
    storageClass: zfs-configs-clusters-k3s-dynamic
    size: 1Gi
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi

replica:
  replicaCount: 0
