---
replicaCount: 1

image:
  repository: ad4mts/zfdash
  pullPolicy: IfNotPresent
  tag: latest

persistence:
  data:
    enabled: true
    storageClass: zfs-vm-pool-dynamic
    size: 1Gi
  config:
    enabled: true
    storageClass: zfs-vm-pool-dynamic
    size: 1Gi

resources:
  requests:
    cpu: 5m
    memory: 64Mi
  limits:
    memory: 128Mi

ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-ca
  hosts:
    - host: zfdash.ref+envsubst://$LOCAL_DOMAIN_NAME
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - zfdash.ref+envsubst://$LOCAL_DOMAIN_NAME
      secretName: zfdash-mkcert-tls
