---
repositories:
  - name: projecthelena
    url: https://charts.projecthelena.com

releases:
  - name: warden
    namespace: warden
    createNamespace: true
    chart: projecthelena/warden
    version: 0.2.3
    values:
      - values.yaml
    hooks:
      - events:
          - presync
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - vals eval -f manifests/secret.yaml | kubectl apply -f -
      - events:
          - postuninstall
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - vals eval -f manifests/secret.yaml | kubectl delete -f -
