image:
  repository: ghcr.io/esanchezm/prometheus-qbittorrent-exporter
  tag: v1.6.0
  pullPolicy: IfNotPresent

qbittorrent:
  host: ""
  port: 8080
  username: ""
  password: ""

service:
  port: 8000

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  release: ""

resources: {}
