apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracearr.fullname" . }}-secret
  labels:
    {{- include "tracearr.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.jwtSecret }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.cookieSecret }}
  COOKIE_SECRET: {{ .Values.secrets.cookieSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.database.password }}
  DATABASE_URL: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.database.user .Values.secrets.database.password .Values.database.host .Values.database.port .Values.database.name | quote }}
  {{- end }}
