---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media-library-arr
spec:
  storageClassName: zfs-tank-media-arr
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /mnt/tank/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - joi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: arr
spec:
  storageClassName: zfs-tank-media-arr
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media-library-media-center
spec:
  storageClassName: zfs-tank-media-media-center
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /mnt/tank/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - joi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: media-center
spec:
  storageClassName: zfs-tank-media-media-center
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media-library-qbittorrent
spec:
  storageClassName: zfs-tank-media-qbittorrent
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /mnt/tank/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - joi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: qbittorrent-vpn
spec:
  storageClassName: zfs-tank-media-qbittorrent
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-immich-library
spec:
  storageClassName: zfs-tank-immich-library
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /mnt/tank/media/photos/immich
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - joi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-downloads
spec:
  storageClassName: zfs-tank-downloads
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /mnt/tank/media/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - joi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: qbittorrent-vpn
spec:
  storageClassName: zfs-tank-downloads
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
