---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-opencode-workdir
spec:
  storageClassName: sc-opencode-workdir
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: ref+envsubst://$HOME_DIR/projects
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ref+envsubst://$SINGLE_NODE_NAME
