apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "seafile.fullname" . }}-shared
  labels:
    {{- include "seafile.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.shared.storageClass }}
  storageClassName: {{ .Values.persistence.shared.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.shared.size }}
{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "seafile.fullname" . }}-data
  labels:
    {{- include "seafile.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | default "10Gi" }}
{{- end }}
