apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zublo.fullname" . }}-secret
  labels:
    {{- include "zublo.labels" . | nindent 4 }}
type: Opaque
stringData:
  PB_ENCRYPTION_KEY: {{ required "secrets.PB_ENCRYPTION_KEY is required" .Values.secrets.PB_ENCRYPTION_KEY | quote }}
