---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-configs-clusters-k3s-dynamic
allowVolumeExpansion: true
parameters:
  poolname: configs/clusters/k3s
  fstype: zfs
  recordsize: 128k
  compression: lz4
  dedup: 'off'
provisioner: zfs.csi.openebs.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
