---
releases:
  - name: vibe-kanban
    namespace: vibe-kanban
    createNamespace: true
    chart: ./charts/vibe-kanban
    values:
      - values.yaml
    hooks:
      - events:
          - presync
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - vals eval -f manifests/pv.yaml | kubectl apply -f -
      - events:
          - postuninstall
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - vals eval -f manifests/pv.yaml | kubectl delete -f -
