---
auth:
  rootPassword: ref+scw:///homelab/seafile#/mariadb-root-password

primary:
  persistence:
    enabled: true
    storageClass: zfs-vm-pool-dynamic
    size: 5Gi
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi

secondary:
  replicaCount: 0
