---
image:
  repository: burakince/mlflow
  pullPolicy: IfNotPresent

backendStore:
  databaseMigration: true
  databaseConnectionCheck: true
  postgres:
    enabled: true
    host: cnpg-cluster0-rw.cnpg-clusters.svc.cluster.local
    port: 5432
    database: mlflow
    user: mlflow
    password: ref+scw:///homelab/cnpg#/mlflow-password

artifactRoot:
  proxiedArtifactStorage: true
  s3:
    enabled: true
    bucket: mlflow-artifacts
    awsAccessKeyId: ref+scw:///homelab/rustfs#/user
    awsSecretAccessKey: ref+scw:///homelab/rustfs#/password

log:
  enabled: false

extraArgs:
  allowedHosts: ref+envsubst://mlflow.$LOCAL_DOMAIN_NAME,mlflow.$PUBLIC_DOMAIN_NAME,mlflow.mlflow.svc.cluster.local

extraEnvVars:
  MLFLOW_S3_ENDPOINT_URL: http://rustfs-svc.rustfs.svc.cluster.local:9000
  MLFLOW_S3_IGNORE_TLS: 'true'

auth:
  enabled: true
  adminUsername: ref+scw:///homelab/mlflow#/admin-username
  adminPassword: ref+scw:///homelab/mlflow#/admin-password
flaskServerSecretKey: ref+scw:///homelab/mlflow#/flask-secret-key

service:
  enabled: true
  type: ClusterIP
  port: 80
  containerPort: 5000

resources:
  requests:
    cpu: 10m
    memory: 256Mi
  limits:
    memory: 1Gi

ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-ca
  hosts:
    - host: mlflow.ref+envsubst://$LOCAL_DOMAIN_NAME
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - mlflow.ref+envsubst://$LOCAL_DOMAIN_NAME
      secretName: mlflow-mkcert-tls

serviceMonitor:
  enabled: true
  namespace: monitoring
  labels:
    release: monitoring
