---
replicaCount: 1

image:
  repository: glanceapp/glance
  pullPolicy: IfNotPresent
  tag: latest

domainName: ''
gluetunUrl: ''
gluetunApiKey: ''
qbittorrentUrl: ''
wardenUrl: ''
wardenApiKey: ''

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts: []
  tls: []

persistence:
  enabled: false
  storageClass: ''
  size: 1Gi

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  TZ: Europe/Paris

glance:
  auth:
    secretKey: ''
    users:
      admin:
        password: ''
  commonBookmarkGroups: []
  instanceBookmarkGroups: []
