---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-home
  annotations:
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: "/home/k"
    openebs.io/cas-type: local
allowVolumeExpansion: true
provisioner: openebs.io/local
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
