---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-vm-pool-dynamic
allowVolumeExpansion: true
parameters:
  poolname: vm-pool
  fstype: zfs
  recordsize: 128k
  compression: lz4
  dedup: 'off'
provisioner: zfs.csi.openebs.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
