---
replicaCount: 1

image:
  repository: ghcr.io/papra-hq/papra
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 1221

ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts: []
  tls: []

persistence:
  enabled: true
  storageClass: ''
  size: 5Gi

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

config:
  TZ: UTC

secrets:
  AUTH_SECRET: ''
