---
apiVersion: v1
kind: Secret
metadata:
  name: rustfs-cnpg-credentials
  namespace: cnpg-clusters
type: Opaque
stringData:
  ACCESS_KEY_ID: ref+scw:///homelab/rustfs#/user
  ACCESS_SECRET_KEY: ref+scw:///homelab/rustfs#/password
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cnpg-rustfs-store
  namespace: cnpg-clusters
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://cnpg-backups/
    endpointURL: http://rustfs-svc.rustfs.svc.cluster.local:9000
    s3Credentials:
      accessKeyId:
        name: rustfs-cnpg-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: rustfs-cnpg-credentials
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
      maxParallel: 2
    data:
      compression: gzip
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-cluster0-daily
  namespace: cnpg-clusters
spec:
  schedule: 0 0 2 * * *
  backupOwnerReference: self
  cluster:
    name: cnpg-cluster0
  immediate: true
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
