---
apiVersion: v1
kind: Secret
metadata:
  name: minio-cnpg-credentials
  namespace: cnpg-clusters
type: Opaque
stringData:
  ACCESS_KEY_ID: ref+passbolt://9a61edf4-633a-4244-ba7f-cfe762b5fa85#/custom_fields/ROOT_USER
  ACCESS_SECRET_KEY: ref+passbolt://9a61edf4-633a-4244-ba7f-cfe762b5fa85#/custom_fields/ROOT_PASSWORD
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cnpg-minio-store
  namespace: cnpg-clusters
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://cnpg-backups/
    endpointURL: http://minio.minio.svc.cluster.local:9000
    s3Credentials:
      accessKeyId:
        name: minio-cnpg-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: minio-cnpg-credentials
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
      maxParallel: 2
    data:
      compression: gzip
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-cluster0-daily
  namespace: cnpg-clusters
spec:
  schedule: 0 0 2 * * *
  backupOwnerReference: self
  cluster:
    name: cnpg-cluster0
  immediate: true
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
