---
apiVersion: v1
kind: Secret
metadata:
  name: gotify-cnpg-credentials
  namespace: cnpg-clusters
  labels:
    cnpg.io/reload: 'true'
type: kubernetes.io/basic-auth
stringData:
  username: gotify
  password: ref+scw:///homelab/cnpg#/gotify-password
---
apiVersion: v1
kind: Secret
metadata:
  name: gotify-cnpg-credentials
  namespace: gotify
  labels:
    cnpg.io/reload: 'true'
type: kubernetes.io/basic-auth
stringData:
  username: gotify
  password: ref+scw:///homelab/cnpg#/gotify-password
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: gotify
  namespace: cnpg-clusters
spec:
  name: gotify
  owner: gotify
  cluster:
    name: cnpg-cluster0
