---
apiVersion: v1
kind: Secret
metadata:
  name: immich-cnpg-credentials
  namespace: immich
  labels:
    cnpg.io/reload: 'true'
type: kubernetes.io/basic-auth
stringData:
  username: immich
  password: ref+envsubst://$CLOUDNATIVE_PG_IMMICH_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-cnpg-credentials
  namespace: cnpg-clusters
  labels:
    cnpg.io/reload: 'true'
type: kubernetes.io/basic-auth
stringData:
  username: immich
  password: ref+envsubst://$CLOUDNATIVE_PG_IMMICH_PASSWORD
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
  namespace: cnpg-clusters
spec:
  name: immich
  owner: immich
  cluster:
    name: cnpg-cluster0
