---
apiVersion: v1
kind: Secret
metadata:
  name: kan-cnpg-credentials
  namespace: cnpg-clusters
  labels:
    cnpg.io/reload: 'true'
type: kubernetes.io/basic-auth
stringData:
  username: kan
  password: ref+passbolt://92595b76-c01e-44f2-a47c-3e1508074331#/custom_fields/CNPG_PASSWORD
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: kan
  namespace: cnpg-clusters
spec:
  name: kan
  owner: kan
  cluster:
    name: cnpg-cluster0
