---
apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-cnpg-credentials
  namespace: cnpg-clusters
  labels:
    cnpg.io/reload: 'true'
type: kubernetes.io/basic-auth
stringData:
  username: linkwarden
  password: ref+passbolt://1211d9f5-8688-44ab-b149-b14e9559bd62#/custom_fields/CNPG_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-cnpg-credentials
  namespace: linkwarden
  labels:
    cnpg.io/reload: 'true'
type: kubernetes.io/basic-auth
stringData:
  username: linkwarden
  password: ref+passbolt://1211d9f5-8688-44ab-b149-b14e9559bd62#/custom_fields/CNPG_PASSWORD
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: linkwarden
  namespace: cnpg-clusters
spec:
  name: linkwarden
  owner: linkwarden
  cluster:
    name: cnpg-cluster0
