---
apiVersion: v1
kind: Secret
metadata:
  name: linkding-cnpg-credentials
  namespace: cnpg-clusters
  labels:
    cnpg.io/reload: 'true'
type: kubernetes.io/basic-auth
stringData:
  username: linkding
  password: ref+scw:///homelab/cnpg#/linkding-password
---
apiVersion: v1
kind: Secret
metadata:
  name: linkding-cnpg-credentials
  namespace: linkding
  labels:
    cnpg.io/reload: 'true'
type: kubernetes.io/basic-auth
stringData:
  username: linkding
  password: ref+scw:///homelab/cnpg#/linkding-password
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: linkding
  namespace: cnpg-clusters
spec:
  name: linkding
  owner: linkding
  cluster:
    name: cnpg-cluster0
