---
apiVersion: v1
kind: Secret
metadata:
  name: memos-cnpg-credentials
  namespace: cnpg-clusters
  labels:
    cnpg.io/reload: 'true'
type: kubernetes.io/basic-auth
stringData:
  username: memos
  password: ref+scw:///homelab/cnpg#/memos-password
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: memos
  namespace: cnpg-clusters
spec:
  name: memos
  owner: memos
  cluster:
    name: cnpg-cluster0
