---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-cnpg-credentials
  namespace: cnpg-clusters
  labels:
    cnpg.io/reload: 'true'
type: kubernetes.io/basic-auth
stringData:
  username: mlflow
  password: ref+envsubst://$CLOUDNATIVE_PG_MLFLOW_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-cnpg-credentials
  namespace: mlflow
  labels:
    cnpg.io/reload: 'true'
type: kubernetes.io/basic-auth
stringData:
  username: mlflow
  password: ref+envsubst://$CLOUDNATIVE_PG_MLFLOW_PASSWORD
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: mlflow
  namespace: cnpg-clusters
spec:
  name: mlflow
  owner: mlflow
  cluster:
    name: cnpg-cluster0
