---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-cnpg-credentials
  namespace: cnpg-clusters
  labels:
    cnpg.io/reload: 'true'
type: kubernetes.io/basic-auth
stringData:
  username: n8n
  password: ref+passbolt://d1997ce8-1b15-4658-b057-8e8f82d1adb3#/custom_fields/CNPG_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-cnpg-credentials
  namespace: n8n
  labels:
    cnpg.io/reload: 'true'
type: kubernetes.io/basic-auth
stringData:
  username: n8n
  password: ref+passbolt://d1997ce8-1b15-4658-b057-8e8f82d1adb3#/custom_fields/CNPG_PASSWORD
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: n8n
  namespace: cnpg-clusters
spec:
  name: n8n
  owner: n8n
  cluster:
    name: cnpg-cluster0
