---
apiVersion: v1
kind: Secret
metadata:
  name: passbolt-cnpg-credentials
  namespace: cnpg-clusters
  labels:
    cnpg.io/reload: 'true'
type: kubernetes.io/basic-auth
stringData:
  username: passbolt
  password: ref+envsubst://$CLOUDNATIVE_PG_PASSBOLT_PASSWORD
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: passbolt
  namespace: cnpg-clusters
spec:
  name: passbolt
  owner: passbolt
  cluster:
    name: cnpg-cluster0
