---
apiVersion: v1
kind: Secret
metadata:
  name: tracearr-cnpg-credentials
  namespace: tracearr
  labels:
    cnpg.io/reload: 'true'
type: kubernetes.io/basic-auth
stringData:
  username: tracearr
  password: ref+scw:///homelab/cnpg#/tracearr-password
---
apiVersion: v1
kind: Secret
metadata:
  name: tracearr-cnpg-credentials
  namespace: cnpg-clusters
  labels:
    cnpg.io/reload: 'true'
type: kubernetes.io/basic-auth
stringData:
  username: tracearr
  password: ref+scw:///homelab/cnpg#/tracearr-password
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: tracearr
  namespace: cnpg-clusters
spec:
  name: tracearr
  owner: tracearr
  cluster:
    name: cnpg-cluster0
