---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nfs-server.fullname" . }}
  labels:
    {{- include "nfs-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nfs-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nfs-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: nfs-vol
          hostPath:
            path: {{ .Values.hostPath }}
            type: Directory
      restartPolicy: Always
      containers:
        - name: nfs-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SHARED_DIRECTORY
              value: /nfsshare
          ports:
            - name: nfs
              containerPort: 2049
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /nfsshare
              name: nfs-vol
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
