---
controllers:
  main:
    containers:
      main:
        image:
          tag: v2.5.6
        resources:
          requests:
            cpu: 10m
            memory: 1Gi
          limits:
            memory: 2Gi
        env:
          REDIS_HOSTNAME: '{{ printf "%s-valkey" .Release.Name }}'
          IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
          DB_USERNAME: immich
          DB_PASSWORD: ref+envsubst://$CLOUDNATIVE_PG_IMMICH_PASSWORD
          DB_DATABASE_NAME: immich
          DB_HOSTNAME: cnpg-cluster0-rw.cnpg-clusters.svc.cluster.local
          DB_PORT: '5432'

immich:
  metrics:
    enabled: true
  persistence:
    library:
      existingClaim: media-library
  configuration: {}

valkey:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 8Mi
    limits:
      memory: 64Mi
  persistence:
    data:
      enabled: true
      size: 1Gi
      type: persistentVolumeClaim
      storageClass: zfs-vm-pool-dynamic
      accessMode: ReadWriteOnce

machine-learning:
  enabled: true
  controllers:
    main:
      containers:
        main:
          resources:
            requests:
              cpu: 10m
              memory: 512Mi
            limits:
              memory: 2Gi
  defaultPodOptions:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
  persistence:
    cache:
      enabled: true
      size: 10Gi
      type: persistentVolumeClaim
      storageClass: zfs-vm-pool-dynamic
      accessMode: ReadWriteOnce

server:
  defaultPodOptions:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: mkcert-ca
      hosts:
        - host: immich.ref+envsubst://$LOCAL_DOMAIN_NAME
          paths:
            - path: /
      tls:
        - hosts:
            - immich.ref+envsubst://$LOCAL_DOMAIN_NAME
          secretName: immich-mkcert-tls
