---
releases:
  - name: dynacat-k8s
    namespace: dynacat
    createNamespace: true
    chart: oci://ghcr.io/lukasdietrich/glance-k8s/chart/glance-k8s
    version: v0.4.9
    values:
      - fullnameOverride: dynacat-k8s

  - name: dynacat-public
    namespace: dynacat
    createNamespace: true
    chart: ./charts/dynacat
    values:
      - values-common.yaml
      - values-public.yaml
      - domainName: ref+envsubst://$PUBLIC_DOMAIN_NAME
      - dynacat:
          auth:
            secretKey: ref+scw:///homelab/dynacat#/auth-secret-key
            users:
              admin:
                password: ref+scw:///homelab/dynacat#/admin-password

  - name: dynacat-local
    namespace: dynacat
    chart: ./charts/dynacat
    values:
      - values-common.yaml
      - values-local.yaml
      - domainName: ref+envsubst://$LOCAL_DOMAIN_NAME
      - dynacat:
          auth:
            secretKey: ref+scw:///homelab/dynacat#/auth-secret-key
            users:
              admin:
                password: ref+scw:///homelab/dynacat#/admin-password
      - ingress:
          hosts:
            - host: dashboard.ref+envsubst://$LOCAL_DOMAIN_NAME
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - dashboard.ref+envsubst://$LOCAL_DOMAIN_NAME
              secretName: dynacat-local-mkcert-tls
