---
replicaCount: 1

image:
  repository: ghcr.io/kanbn/kan
  pullPolicy: IfNotPresent
  tag: latest
domainName: '{{ .Values.domainName }}'

kan:
  baseUrl: https://kan.home.arpa
  authSecret: ref+file://../../../_secret.yaml#/kan/authSecret
  allowCredentials: true

postgres:
  host: cnpg-database-cluster-rw.cnpg-database.svc.cluster.local
  port: 5432
  database: kan_db
  user: kan_user
  password: ref+file://../../../_secret.yaml#/kan/postgresUrl/password

ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-ca
  hosts:
    - host: kan.home.arpa
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - kan.home.arpa
      secretName: kan-mkcert-tls
