---
replicaCount: 1

image:
  repository: ghcr.io/kanbn/kan
  pullPolicy: IfNotPresent
  tag: latest
domainName: '{{ .Values.domainName }}'

kan:
  baseUrl: https://kan.ref+envsubst://$LOCAL_DOMAIN_NAME
  authSecret: ref+envsubst://$KAN_AUTHSECRET
  allowCredentials: true

postgres:
  host: cnpg-cluster0-rw.cnpg-clusters.svc.cluster.local
  port: 5432
  database: kan
  user: kan
  password: ref+envsubst://$KAN_POSTGRESURL_PASSWORD

ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-ca
  hosts:
    - host: kan.ref+envsubst://$LOCAL_DOMAIN_NAME
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - kan.ref+envsubst://$LOCAL_DOMAIN_NAME
      secretName: kan-mkcert-tls
