---
replicaCount: 1

openchamber:
  image:
    repository: oven/bun
    pullPolicy: IfNotPresent
    tag: debian
  initImage:
    repository: oven/bun
    pullPolicy: IfNotPresent
    tag: debian
  package: "@openchamber/web"
  port: 3000

extraPackages: []

postInstall: []

persistence:
  workdir:
    storageClass: sc-opencode-workdir
    accessMode: ReadWriteOnce
    size: 100Gi
  config:
    storageClass: zfs-vm-pool-dynamic
    accessMode: ReadWriteOnce
    size: 5Gi
  worktree:
    storageClass: sc-opencode-worktree
    accessMode: ReadWriteOnce
    size: 10Gi


service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts: []
  tls: []

resources:
  openchamber: {}

podSecurityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}

env: {}
