apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-vpn-proton
  namespace: qbittorrent-vpn
type: Opaque
stringData:
  username: ref+bw://6559131c-335c-438b-8553-ade100c46c4c/proton-openvpn-username
  password: ref+bw://6559131c-335c-438b-8553-ade100c46c4c/proton-openvpn-password

