apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "musicbrainz-picard.fullname" . }}-config
  labels:
    {{- include "musicbrainz-picard.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: zfs-vm-pool-dynamic
  resources:
    requests:
      storage: 1Gi
