---
postgres:
  enabled: false
  external:
    enabled: true
    uri: ref+scw:///homelab/linkwarden#/database-uri

configuration:
  authentication:
    disableRegistration: false
    PublicCredentialsEnabled: true
    disableNewSSOUsers: true
    authURL: http://localhost:3000/api/v1/auth
    authSecret: ref+scw:///homelab/linkwarden#/auth-secret

persistence:
  enabled: true
  storageClass: zfs-vm-pool-dynamic
  accessMode: ReadWriteOnce
  size: 2Gi

resources:
  requests:
    cpu: 10m
    memory: 768Mi
  limits:
    memory: 1536Mi

ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-ca
  hosts:
    - host: linkwarden.ref+envsubst://$LOCAL_DOMAIN_NAME
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - linkwarden.ref+envsubst://$LOCAL_DOMAIN_NAME
      secretName: linkwarden-mkcert-tls
