---
postgres:
  enabled: false
  external:
    enabled: true
    uri: ref+passbolt://1211d9f5-8688-44ab-b149-b14e9559bd62#/custom_fields/CNPG_URI

configuration:
  authentication:
    disableRegistration: false
    PublicCredentialsEnabled: true
    disableNewSSOUsers: true
    authURL: http://localhost:3000/api/v1/auth
    authSecret: ref+passbolt://1211d9f5-8688-44ab-b149-b14e9559bd62#/custom_fields/AUTHSECRET

ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-ca
  hosts:
    - host: linkwarden.home.arpa
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - linkwarden.home.arpa
      secretName: linkwarden-mkcert-tls
