---
apiVersion: v1
kind: Service
metadata:
  name: openclaw-host
spec:
  ports:
    - port: 18789
      targetPort: 18789
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: openclaw-host
subsets:
  - addresses:
      - ip: ref+envsubst://$SINGLE_NODE_IP
    ports:
      - port: 18789
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openclaw
  annotations:
    cert-manager.io/cluster-issuer: mkcert-ca
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - openclaw.ref+envsubst://$LOCAL_DOMAIN_NAME
      secretName: openclaw-mkcert-tls
  rules:
    - host: openclaw.ref+envsubst://$LOCAL_DOMAIN_NAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openclaw-host
                port:
                  number: 18789
