---
replicaCount: 1

image:
  repository: corentinth/it-tools
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
