---
repositories:
  - name: infisical-helm-charts
    url: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
releases:
  - name: infisical
    namespace: infisical
    createNamespace: true
    chart: infisical-helm-charts/infisical-standalone
    version: 1.7.2
    values:
      - values.yaml
