---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-themes
  namespace: home-assistant
data:
  soft-ui.yaml: |-
    soft-ui:
      card-mod-theme: soft-ui
      card-mod-card: |
        ha-card {
          margin: 20px;
          border-radius: 15px;
          background-color: var(--primary-background-color);
          box-shadow: -5px -5px 15px # ffffff, 5px 5px 15px  # ebebeb;
        }
      soft-ui-pressed: "inset -4px -4px 5px #ffffff, inset 4px 4px 5px #ebebeb"
      modes:
        dark:
          primary-background-color: "#212121"
          card-background-color: "#212121"
          primary-text-color: "#e1e1e1"
          secondary-text-color: "#9b9b9b"
          primary-color: "#3b82f6"
          divider-color: "#2c2c2c"
          card-mod-card: |
            ha-card {
              margin: 20px;
              border-radius: 15px;
              background-color: var(--primary-background-color);
              box-shadow: -5px -5px 15px # 2c2c2c, 5px 5px 15px  # 191919;
            }
          soft-ui-pressed: "inset -4px -4px 5px #2c2c2c, inset 4px 4px 5px #191919"
