---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-admindb-secret
  namespace: cnpg-clusters
type: Opaque
stringData:
  username: ref+scw:///homelab/cnpg#/username
  password: ref+scw:///homelab/cnpg#/password
