---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-admindb-secret
  namespace: cnpg-clusters
type: Opaque
stringData:
  username: ref+envsubst://$CLOUDNATIVE_PG_USERNAME
  password: ref+envsubst://$CLOUDNATIVE_PG_PASSWORD
