---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-admindb-secret
  namespace: cnpg-clusters
type: Opaque
stringData:
  username: ref+passbolt://8aa635b5-a13a-4b41-8298-00a35b7ee2d7#/custom_fields/ADMIN_USERNAME
  password: ref+passbolt://8aa635b5-a13a-4b41-8298-00a35b7ee2d7#/custom_fields/ADMIN_PASSWORD
