---
repositories:
  - name: rustfs
    url: https://charts.rustfs.com/
releases:
  - name: rustfs
    namespace: rustfs
    createNamespace: true
    chart: rustfs/rustfs
    version: 0.0.99
    values:
      - values.yaml
    hooks:
      - events:
          - presync
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - kubectl create namespace rustfs --dry-run=client -o yaml | kubectl apply -f - && vals eval
            -f manifests/secret.yaml | kubectl apply -f -
      - events:
          - postuninstall
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - vals eval -f manifests/secret.yaml | kubectl delete -f -
