apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linkding.fullname" . }}-secret
  labels:
    {{- include "linkding.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.LD_SUPERUSER_NAME }}
  LD_SUPERUSER_NAME: {{ .Values.secrets.LD_SUPERUSER_NAME | quote }}
  {{- end }}
  {{- if .Values.secrets.LD_SUPERUSER_PASSWORD }}
  LD_SUPERUSER_PASSWORD: {{ .Values.secrets.LD_SUPERUSER_PASSWORD | quote }}
  {{- end }}
  {{- if .Values.secrets.LD_SECRET_KEY }}
  LD_SECRET_KEY: {{ .Values.secrets.LD_SECRET_KEY | quote }}
  {{- end }}
  {{- if .Values.secrets.OIDC_RP_CLIENT_SECRET }}
  OIDC_RP_CLIENT_SECRET: {{ .Values.secrets.OIDC_RP_CLIENT_SECRET | quote }}
  {{- end }}
  {{- if .Values.secrets.database.password }}
  LD_DB_PASSWORD: {{ .Values.secrets.database.password | quote }}
  {{- end }}
