---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: minio
type: Opaque
stringData:
  rootUser: ref+passbolt://9a61edf4-633a-4244-ba7f-cfe762b5fa85#/custom_fields/ROOT_USER
  rootPassword: ref+passbolt://9a61edf4-633a-4244-ba7f-cfe762b5fa85#/custom_fields/ROOT_PASSWORD
