---
service:
  type: NodePort
  port: 8096
  nodePort: 30096

persistence:
  config:
    enabled: true
    storageClass: zfs-vm-pool-dynamic
    size: 40Gi
  media:
    enabled: true
    existingClaim: media-library
  cache:
    enabled: true
    storageClass: zfs-vm-pool-dynamic
    size: 20Gi
    mountPath: /cache

# for hardware acceleration
podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  supplementalGroups:
    - 993
  capabilities:
    add:
      - SYS_ADMIN
    drop:
      - ALL
  privileged: false

extraVolumes:
  - name: hwa
    hostPath:
      path: /dev/dri

extraVolumeMounts:
  - name: hwa
    mountPath: /dev/dri

resources:
  requests:
    cpu: 10m
    memory: 512Mi
    gpu.intel.com/i915: '1'
  limits:
    memory: 2Gi
    gpu.intel.com/i915: '1'

ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-ca
  hosts:
    - host: jellyfin.ref+envsubst://$LOCAL_DOMAIN_NAME
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - jellyfin.ref+envsubst://$LOCAL_DOMAIN_NAME
      secretName: jellyfin-mkcert-tls
