---
apiVersion: v1
kind: Secret
metadata:
  name: memos-db-dsn
  namespace: memos
type: Opaque
stringData:
  dsn: postgres://memos:ref+scw:///homelab/cnpg#/memos-password+@cnpg-cluster0-rw.cnpg-clusters.svc.cluster.local:5432/memos
