---
apiVersion: v1
kind: Secret
metadata:
  name: memos-db-dsn
  namespace: memos
type: Opaque
stringData:
  dsn: ref+envsubst://postgres://memos:$CLOUDNATIVE_PG_MEMOS_PASSWORD@cnpg-cluster0-rw.cnpg-clusters.svc.cluster.local:5432/memos
