---
repositories:
  - name: rtomik-helm-charts
    url: https://rtomik.github.io/helm-charts

releases:
  - name: qbittorrent-vpn
    namespace: qbittorrent-vpn
    createNamespace: true
    chart: rtomik-helm-charts/qbittorrent-vpn
    version: 0.0.2
    values:
      - values.yaml
    hooks:
      - events:
          - presync
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - vals eval -f manifests/secret.yaml | kubectl apply -f -
      - events:
          - presync
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - vals eval -f manifests/gluetun-api-svc.yaml | kubectl apply -f -
      - events:
          - postuninstall
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - vals eval -f manifests/secret.yaml | kubectl delete -f -
      - events:
          - postuninstall
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - vals eval -f manifests/gluetun-api-svc.yaml | kubectl delete -f -
