---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pgadmin-data
  namespace: pgadmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: zfs-vm-pool-pgadmin
