---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-admin
  namespace: pgadmin
type: Opaque
stringData:
  password: ref+passbolt://32eb115d-bfa3-4871-807f-3977e885ce4d#/custom_fields/ADMIN_PASSWORD
