---
apiVersion: v1
kind: Secret
metadata:
  name: newt-credentials
  namespace: fossorial
type: Opaque
stringData:
  PANGOLIN_ENDPOINT: ref+envsubst://$PANGOLIN_ENDPOINT
  NEWT_ID: ref+envsubst://$PANGOLIN_ID
  NEWT_SECRET: ref+envsubst://$PANGOLIN_SECRET
