---
apiVersion: v1
kind: Secret
metadata:
  name: newt-credentials
  namespace: fossorial
type: Opaque
stringData:
  PANGOLIN_ENDPOINT: https://pangolin.ref+envsubst://$PUBLIC_DOMAIN_NAME
  NEWT_ID: ref+scw:///homelab/pangolin#/id
  NEWT_SECRET: ref+scw:///homelab/pangolin#/secret
