{{- range $appName, $app := .Values.apps }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restic-backups.secretName" (dict "appName" $appName "app" $app) }}
  namespace: {{ $app.namespace }}
  labels:
    {{- include "restic-backups.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $appName }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ $.Values.credentials.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ $.Values.credentials.secretAccessKey }}
  RESTIC_PASSWORD: {{ $.Values.credentials.resticPassword }}
  RESTIC_REPOSITORY: {{ include "restic-backups.resticRepo" (dict "global" $.Values "appName" $appName) }}
{{- end }}
