---
repositories:
  - name: zekker6
    url: https://zekker6.github.io/helm-charts/

releases:
  - name: changedetection-io
    namespace: changedetection-io
    createNamespace: true
    chart: zekker6/changedetection-io
    version: 1.93.0
    values:
      - values.yaml
