---
env:
  TZ: Europe/Paris

persistence:
  config:
    enabled: true
    type: pvc
    mountPath: /config
    readOnly: false
    storageClass: zfs-vm-pool-dynamic
    size: 1Gi
  media:
    enabled: true
    type: pvc
    mountPath: /media
    readOnly: false
    existingClaim: media-library

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

resources:
  requests:
    cpu: 10m
    memory: 192Mi
  limits:
    memory: 512Mi

ingress:
  main:
    enabled: true
    primary: true
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: mkcert-ca
    labels: {}
    ingressClassName: traefik
    hosts:
      - host: bazarr.ref+envsubst://$LOCAL_DOMAIN_NAME
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - bazarr.ref+envsubst://$LOCAL_DOMAIN_NAME
        secretName: bazarr-mkcert-tls
