---
repositories:
  - name: fossorial
    url: https://charts.fossorial.io

releases:
  - name: fossorial
    namespace: fossorial
    createNamespace: true
    chart: fossorial/newt
    version: 1.3.0
    values:
      - values.yaml
    hooks:
      - events:
          - presync
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f - && vals
            eval -f manifests/secret.yaml | kubectl apply -f - && vals eval -f manifests/blueprint.yaml
            | kubectl apply -f -
      - events:
          - postuninstall
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - vals eval -f manifests/secret.yaml | kubectl delete -f - && vals eval -f manifests/blueprint.yaml
            | kubectl delete -f -
