---
apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-grafana-admin
type: Opaque
stringData:
  username: ref+envsubst://$KUBE_PROMETHEUS_STACK_GRAFANA_ADMIN_USERNAME
  password: ref+envsubst://$KUBE_PROMETHEUS_STACK_GRAFANA_ADMIN_PASSWORD
