---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: minio
type: Opaque
stringData:
  rootUser: ref+envsubst://$MINIO_ROOT_USER
  rootPassword: ref+envsubst://$MINIO_ROOT_PASSWORD
