---
redisDependencyEnabled: true
mariadbDependencyEnabled: false
postgresqlDependencyEnabled: false

replicaCount: 1

app:
  database:
    kind: postgresql
  cache:
    redis:
      enabled: true
      sentinelProxy:
        enabled: false
jwtCreateKeysForced: true

passboltEnv:
  plain:
    APP_FULL_BASE_URL: https://passbolt.home.arpa
    PASSBOLT_SSL_FORCE: 'false'
    PASSBOLT_REGISTRATION_PUBLIC: 'true'
    PASSBOLT_PLUGINS_JWT_AUTHENTICATION_ENABLED: 'true'
    PASSBOLT_KEY_EMAIL: ref+envsubst://$EMAIL_ADDRESS
    DEBUG: 'false'
    DATASOURCES_DEFAULT_HOST: cnpg-cluster0-rw.cnpg-clusters.svc.cluster.local
    DATASOURCES_DEFAULT_PORT: '5432'
    CACHE_DEFAULT_HOST: passbolt-redis-master
    CACHE_CAKECORE_HOST: passbolt-redis-master
    CACHE_CAKEMODEL_HOST: passbolt-redis-master
  secret:
    DATASOURCES_DEFAULT_USERNAME: passbolt
    DATASOURCES_DEFAULT_PASSWORD: ref+envsubst://$CLOUDNATIVE_PG_PASSBOLT_PASSWORD
    DATASOURCES_DEFAULT_DATABASE: passbolt
    CACHE_DEFAULT_PASSWORD: ref+envsubst://$PASSBOLT_REDIS_PASSWORD
    CACHE_CAKECORE_PASSWORD: ref+envsubst://$PASSBOLT_REDIS_PASSWORD
    CACHE_CAKEMODEL_PASSWORD: ref+envsubst://$PASSBOLT_REDIS_PASSWORD

redis:
  auth:
    password: ref+envsubst://$PASSBOLT_REDIS_PASSWORD
  sentinel:
    enabled: false

cronJobEmail:
  enabled: false

# Override probes to use correct hostname
livenessProbe:
  httpGet:
    port: http
    scheme: HTTP
    path: /healthcheck/status.json
    httpHeaders:
      - name: Host
        value: passbolt.home.arpa
  initialDelaySeconds: 20
  periodSeconds: 10

readinessProbe:
  httpGet:
    port: http
    scheme: HTTP
    path: /healthcheck/status.json
    httpHeaders:
      - name: Host
        value: passbolt.home.arpa
  initialDelaySeconds: 5
  periodSeconds: 10

ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-ca
  hosts:
    - host: passbolt.home.arpa
      paths:
        - path: /
          pathType: ImplementationSpecific
          port: http
  tls:
    - existingSecret: passbolt-mkcert-tls
      hosts:
        - passbolt.home.arpa
