# helmfile.yaml
repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

apiVersions:
  - monitoring.coreos.com/v1

releases:
  - name: argocd
    namespace: argocd
    createNamespace: true
    chart: argo/argo-cd
    values:
      - commonLabels:
          app.kubernetes.io/managed-by: Helm
          meta.helm.sh/release-name: argocd
          meta.helm.sh/release-namespace: argocd
    # values:
    #   - my-argocd-values.yaml
