FROM golang:1.24 AS building

ARG FRP_VERSION=0.66.0

RUN git clone --depth 1 --branch v${FRP_VERSION} https://github.com/fatedier/frp.git /building
WORKDIR /building

RUN make frps

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frps /usr/bin/frps

ENTRYPOINT ["/usr/bin/frps"]
