---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vibe-kanban
spec:
  storageClassName: sc-vibe-kanban
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: ref+passbolt://21c07ae0-312f-4a0e-b409-81b638918d74#/custom_fields/PV_PATH
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ref+envsubst://$SINGLE_NODE_NAME
