---
releases:
  - name: restic-backups
    chart: ./charts/restic-backups
    values:
      - values.yaml
      - global:
          nodeSelector:
            kubernetes.io/hostname: ref+envsubst://$SINGLE_NODE_NAME
      - credentials:
          accessKeyId: ref+scw:///homelab/rustfs#/user
          secretAccessKey: ref+scw:///homelab/rustfs#/password
          resticPassword: ref+scw:///homelab/restic#/password
