---
releases:
  - name: glance-k8s
    namespace: glance
    createNamespace: true
    chart: oci://ghcr.io/lukasdietrich/glance-k8s/chart/glance-k8s
    version: v0.4.4
    values:
      - fullnameOverride: glance-k8s

  - name: glance-public
    namespace: glance
    createNamespace: true
    chart: ./charts/glance
    values:
      - values-common.yaml
      - values-public.yaml
      - domainName: ref+envsubst://$PUBLIC_DOMAIN_NAME
      - gluetunApiKey: ref+envsubst://$GLUETUN_API_KEY
      - glance:
          auth:
            secretKey: ref+envsubst://$GLANCE_AUTH_SECRET_KEY
            users:
              admin:
                password: ref+envsubst://$GLANCE_AUTH_USERS_ADMIN_PASSWORD

  - name: glance-local
    namespace: glance
    chart: ./charts/glance
    values:
      - values-common.yaml
      - values-local.yaml
      - domainName: ref+envsubst://$LOCAL_DOMAIN_NAME
      - gluetunApiKey: ref+envsubst://$GLUETUN_API_KEY
      - glance:
          auth:
            secretKey: ref+envsubst://$GLANCE_AUTH_SECRET_KEY
            users:
              admin:
                password: ref+envsubst://$GLANCE_AUTH_USERS_ADMIN_PASSWORD
      - ingress:
          hosts:
            - host: dashboard.ref+envsubst://$LOCAL_DOMAIN_NAME
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - dashboard.ref+envsubst://$LOCAL_DOMAIN_NAME
              secretName: glance-local-mkcert-tls
