---
replicaCount: 1

gluetunUrl: ''
gluetunApiKey: ''
qbittorrentUrl: ''
uptimeKumaUrl: ''
uptimeKumaStatusSlug: ''
domainName: ''
localDomain: home.arpa

image:
  repository: glanceapp/glance
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-ca
  hosts:
    - host: dashboard.home.arpa
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - dashboard.home.arpa
      secretName: homarr-mkcert-tls

persistence:
  enabled: false
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  TZ: Europe/Paris

glance:
  pages:
    - name: Public
      domain: DOMAIN_NAME
      showFrp: true
    - name: Local
      domain: LOCAL_DOMAIN
      showFrp: false

  bookmarkGroups:
    - title: Tools
      links:
        - title: Kan.sh
          subdomain: kan
          icon: https://raw.githubusercontent.com/kanbn/kan/refs/heads/main/apps/docs/favicon.png
        - title: Stirling PDF
          subdomain: stirling-pdf
          icon: sh:stirling-pdf
        - title: Linkwarden
          subdomain: linkwarden
          icon: sh:linkwarden
        - title: n8n
          subdomain: n8n
          icon: di:n8n

    - title: Media
      links:
        - title: Jellyfin
          subdomain: jellyfin
          icon: di:jellyfin
        - title: Jellyseerr
          subdomain: jellyseerr
          icon: di:jellyseerr
        - title: Immich
          subdomain: immich
          icon: di:immich

    - title: Downloads
      links:
        - title: qBittorrent
          subdomain: qbittorrent
          icon: di:qbittorrent
        - title: Prowlarr
          subdomain: prowlarr
          icon: di:prowlarr
        - title: Radarr
          subdomain: radarr
          icon: di:radarr
        - title: Sonarr
          subdomain: sonarr
          icon: di:sonarr
        - title: Bazarr
          subdomain: bazarr
          icon: di:bazarr

    - title: Back-office
      links:
        - title: Uptime Kuma
          subdomain: status
          icon: di:uptime-kuma
        - title: FRP dashboard
          subdomain: frp
          icon: di:frp
          publicOnly: true
        - title: pgAdmin
          subdomain: pgadmin
          icon: di:postgresql
        - title: dozzle
          subdomain: dozzle
          icon: di:dozzle
    - title: Tech
      links:
        - title: Vibe-kanban
          subdomain: vibe-kanban
          icon: https://raw.githubusercontent.com/VDuchauffour/homelab/refs/heads/main/kubernetes/apps/glance/assets/favicons/vibe-kanban.png

  sharedWidgets:
    smallColumnLeft:
      - type: calendar
        firstDayOfWeek: monday
      - type: weather
        location: Paris, France
        units: metric
        hourFormat: 24h
      - type: todo

    fullColumn:
      - type: hackerNews
        limit: 10
        collapseAfter: 5

  auth:
    secretKey: ref+file://../../../_secret.yaml#/glance/auth/secret-key
    users:
      admin:
        password: ref+file://../../../_secret.yaml#/glance/auth/users/admin/password
