---
replicaCount: 1

gluetunUrl: ''
gluetunApiKey: ''
qbittorrentUrl: ''
uptimeKumaUrl: ''
uptimeKumaStatusSlug: ''
domainName: '{{ .Values.domainName }}'
localDomain: home.arpa

image:
  repository: glanceapp/glance
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-ca
  hosts:
    - host: dashboard.home.arpa
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - dashboard.home.arpa
      secretName: glance-mkcert-tls

persistence:
  enabled: false
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  TZ: Europe/Paris

glance:
  pages:
    - name: Public
      domain: DOMAIN_NAME
    - name: Local
      domain: LOCAL_DOMAIN
    - name: Stats
      domain: LOCAL_DOMAIN

  commonBookmarkGroups:
    - title: Tools
      links:
        - title: qBittorrent
          subdomain: qbittorrent
          icon: di:qbittorrent
        - title: Kan.sh
          subdomain: kan
          icon: https://raw.githubusercontent.com/kanbn/kan/refs/heads/main/apps/docs/favicon.png
        - title: Stirling PDF
          subdomain: stirling-pdf
          icon: sh:stirling-pdf
        - title: Linkwarden
          subdomain: linkwarden
          icon: sh:linkwarden

    - title: Media
      links:
        - title: Jellyfin
          subdomain: jellyfin
          icon: di:jellyfin
        - title: Jellyseerr
          subdomain: jellyseerr
          icon: di:jellyseerr
        - title: Immich
          subdomain: immich
          icon: di:immich

    - title: Arr
      links:
        - title: Prowlarr
          subdomain: prowlarr
          icon: di:prowlarr
        - title: Radarr
          subdomain: radarr
          icon: di:radarr
        - title: Sonarr
          subdomain: sonarr
          icon: di:sonarr
        - title: Bazarr
          subdomain: bazarr
          icon: di:bazarr
        - title: Lidarr
          subdomain: lidarr
          icon: di:lidarr

    - title: AI
      links:
        - title: n8n
          subdomain: n8n
          icon: di:n8n
        - title: Vibe-kanban
          subdomain: vibe-kanban
          icon: https://raw.githubusercontent.com/VDuchauffour/homelab/refs/heads/main/kubernetes/apps/glance/assets/favicons/vibe-kanban.png

  localOnlyBookmarkGroups:
    - title: Cluster
      links:
        - title: Headlamp
          subdomain: headlamp
          icon: di:headlamp
        - title: Helm Dashboard
          subdomain: helm-dashboard
          icon: di:helm
        - title: pgAdmin
          subdomain: pgadmin
          icon: di:postgresql
        - title: MiniO
          subdomain: minio-console
          icon: di:minio

    - title: Monitoring
      links:
        - title: Uptime Kuma
          subdomain: status
          icon: di:uptime-kuma
        - title: Dozzle
          subdomain: dozzle
          icon: di:dozzle

  publicOnlyBookmarkGroups:
    - title: Proxy
      links:
        - title: FRP dashboard
          subdomain: frp
          icon: di:frp

  sharedWidgets:
    glance:
      - type: bookmarks

    stats:
      - type: calendar
        firstDayOfWeek: monday
      - type: weather
        location: Paris, France
        units: metric
        hourFormat: 24h
      - type: todo
      - type: hackerNews
        limit: 15
        collapseAfter: 10

  auth:
    secretKey: ref+envsubst://$GLANCE_AUTH_SECRET_KEY
    users:
      admin:
        password: ref+envsubst://$GLANCE_AUTH_USERS_ADMIN_PASSWORD
