---
resources:
  requests:
    cpu: 5m
    memory: 16Mi
  limits:
    memory: 64Mi
gluetunUrl: gluetun-api.qbittorrent-vpn.svc.cluster.local:8000
immichUrl: immich-server.immich.svc.cluster.local:2283
gluetunApiKey: ref+scw:///homelab/glance#/gluetun-api-key
immichApiKey: ref+scw:///homelab/immich#/api-key
glance:
  instanceBookmarkGroups:
    - title: Proxy
      links:
        - title: Pangolin
          url: https://pangolin.ref+envsubst://$PUBLIC_DOMAIN_NAME
          icon: di:pangolin
    - title: Cluster
      links:
        - title: Headlamp
          subdomain: headlamp
          icon: di:headlamp
        - title: Helm Dashboard
          subdomain: helm-dashboard
          icon: di:helm
        - title: Passbolt
          subdomain: passbolt
          icon: di:passbolt
        - title: pgAdmin
          subdomain: pgadmin
          icon: di:postgresql
        - title: RustFS
          subdomain: rustfs-console
          icon: di:rustfs
        - title: Pi-hole
          subdomain: pihole
          icon: di:pi-hole
    - title: Monitoring
      links:
        - title: Grafana
          subdomain: grafana
          icon: di:grafana
        - title: Warden
          subdomain: warden
          icon: https://raw.githubusercontent.com/projecthelena/warden/702a44724394d9841d86992b800d8df763023b9b/assets/favicon.svg
        - title: Dozzle
          subdomain: dozzle
          icon: di:dozzle
        - title: ZfDash
          subdomain: zfdash
          icon: https://raw.githubusercontent.com/ad4mts/zfdash/refs/heads/main/src/data/icons/zfs-gui.png
        - title: Scrutiny
          subdomain: scrutiny
          icon: di:scrutiny-light
    - title: ''
      links:
        - title: qBittorrent
          subdomain: grafana
          path: /d/eKyTETFMk/qbittorrent
          icon: di:qbittorrent
        - title: UPS statistics
          subdomain: grafana
          path: /d/j4a-DMWRk/ups-statistics
          icon: di:ups
        - title: Wakapi
          subdomain: grafana
          path: /d/BRqbRfVGz/wakatime
          icon: di:wakapi
        - title: Status
          subdomain: warden
          path: /status/all
          icon: https://raw.githubusercontent.com/projecthelena/warden/702a44724394d9841d86992b800d8df763023b9b/assets/favicon.svg

  sharedWidgets:
    stats:
      - type: calendar
        firstDayOfWeek: monday
      - type: weather
        location: Paris, France
        units: metric
        hourFormat: 24h
      - type: todo

  commonBookmarkGroups:
    - title: Media
      links:
        - title: Jellyfin
          subdomain: jellyfin
          icon: di:jellyfin
        - title: Jellyseerr
          subdomain: jellyseerr
          icon: di:jellyseerr
        - title: Immich
          subdomain: immich
          icon: di:immich
        - title: qBittorrent
          subdomain: qbittorrent
          icon: di:qbittorrent
        - title: Navidrome
          subdomain: navidrome
          icon: di:navidrome
        - title: slskd
          subdomain: slskd
          icon: di:slskd
    - title: Arr
      links:
        - title: Bazarr
          subdomain: bazarr
          icon: di:bazarr
        - title: Radarr
          subdomain: radarr
          icon: di:radarr
        - title: Sonarr
          subdomain: sonarr
          icon: di:sonarr
        - title: Lidarr
          subdomain: lidarr
          icon: di:lidarr
        - title: Prowlarr
          subdomain: prowlarr
          icon: di:prowlarr
        - title: Tdarr
          subdomain: tdarr
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/tdarr.png
    - title: Productivity
      links:
        - title: Kan.sh
          subdomain: kan
          icon: https://raw.githubusercontent.com/kanbn/kan/refs/heads/main/apps/docs/favicon.png
        - title: Linkwarden
          subdomain: linkwarden
          icon: sh:linkwarden
        - title: Linkding
          subdomain: linkding
          icon: sh:linkding
        - title: Memos
          subdomain: memos
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/memos.png
    - title: Tools
      links:
        - title: ChangeDetection
          subdomain: changedetection
          icon: di:changedetection
        - title: Wakapi
          subdomain: wakapi
          icon: di:wakapi
        - title: BentoPDF
          subdomain: bentopdf
          icon: sh:bentopdf
        - title: Stirling PDF
          subdomain: stirling-pdf
          icon: sh:stirling-pdf
    - title: Sharing
      links:
        - title: Filebrowser
          subdomain: filebrowser
          icon: di:filebrowser
        - title: Nextcloud
          subdomain: nextcloud
          icon: di:nextcloud
        - title: Seafile
          subdomain: seafile
          icon: di:seafile
        - title: Privatebin
          subdomain: privatebin
          icon: di:privatebin
    - title: AI
      links:
        - title: n8n
          subdomain: n8n
          icon: di:n8n
        - title: MLflow
          subdomain: mlflow
          icon: di:ml-flow-wordmark-dark
        - title: OpenChamber
          subdomain: openchamber
          icon: https://raw.githubusercontent.com/btriapitsyn/openchamber/20f158f2b71b66aef0235531b5092ba82cda720f/packages/vscode/assets/app-icon.png
        - title: OpenCode
          subdomain: opencode
          icon: di:opencode-dark
