---
repositories:
  - name: collabora-online
    url: https://collaboraonline.github.io/online/

releases:
  - name: collabora
    namespace: collabora
    createNamespace: true
    chart: collabora-online/collabora-online
    version: 1.1.58
    values:
      - values.yaml
