---
fullnameOverride: collabora

collabora:
  aliasgroups:
    - host: https://nextcloud.ref+envsubst://$LOCAL_DOMAIN_NAME:443
    - host: https://nextcloud.ref+envsubst://$PUBLIC_DOMAIN_NAME:443

  server_name: collabora.ref+envsubst://$PUBLIC_DOMAIN_NAME

  username: admin
  password: ref+envsubst://$COLLABORA_ADMIN_PASSWORD

  extra_params: --o:ssl.enable=false --o:ssl.termination=true

ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-ca
  hosts:
    - host: collabora.ref+envsubst://$LOCAL_DOMAIN_NAME
      paths:
        - path: /
          pathType: Prefix
    - host: collabora.ref+envsubst://$PUBLIC_DOMAIN_NAME
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: collabora-mkcert-tls
      hosts:
        - collabora.ref+envsubst://$LOCAL_DOMAIN_NAME
        - collabora.ref+envsubst://$PUBLIC_DOMAIN_NAME

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    memory: 2Gi

autoscaling:
  enabled: false
