---
repositories:
  - name: headlamp
    url: https://kubernetes-sigs.github.io/headlamp/
releases:
  - name: headlamp
    namespace: kube-system
    createNamespace: false
    chart: headlamp/headlamp
    version: 0.40.1
    values:
      - values.yaml
