---
config:
  TZ: Europe/Paris
  LD_CSRF_TRUSTED_ORIGINS: https://linkding.ref+envsubst://$LOCAL_DOMAIN_NAME
  LD_ENABLE_AUTH_PROXY: false
  LD_DISABLE_LOGIN_FORM: false
  database:
    host: cnpg-cluster0-rw.cnpg-clusters.svc.cluster.local
    name: linkding
    user: linkding
    port: '5432'

secrets:
  LD_SUPERUSER_NAME: ref+scw:///homelab/linkding#/superuser-name
  LD_SUPERUSER_PASSWORD: ref+scw:///homelab/linkding#/superuser-password
  LD_SECRET_KEY: ref+scw:///homelab/linkding#/secret-key
  database:
    password: ref+scw:///homelab/cnpg#/linkding-password

persistence:
  enabled: true
  storageClass: zfs-configs-clusters-k3s-dynamic
  size: 1Gi

resources:
  requests:
    cpu: 10m
    memory: 224Mi
  limits:
    memory: 512Mi

image:
  repository: sissbruecker/linkding
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 9090

ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-ca
  hosts:
    - host: linkding.ref+envsubst://$LOCAL_DOMAIN_NAME
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - linkding.ref+envsubst://$LOCAL_DOMAIN_NAME
      secretName: linkding-mkcert-tls
