---
config:
  TZ: Europe/Paris
  LD_CSRF_TRUSTED_ORIGINS: https://linkding.ref+envsubst://$LOCAL_DOMAIN_NAME
  LD_ENABLE_AUTH_PROXY: false
  LD_DISABLE_LOGIN_FORM: false
  database:
    host: cnpg-cluster0-rw.cnpg-clusters.svc.cluster.local
    name: linkding
    user: linkding
    port: '5432'

secrets:
  LD_SUPERUSER_NAME: ref+passbolt://b94f5947-62fd-40d3-8afd-1eadae695fbb#/custom_fields/SUPERUSER_NAME
  LD_SUPERUSER_PASSWORD: ref+passbolt://b94f5947-62fd-40d3-8afd-1eadae695fbb#/custom_fields/SUPERUSER_PASSWORD
  LD_SECRET_KEY: ref+passbolt://b94f5947-62fd-40d3-8afd-1eadae695fbb#/custom_fields/SECRET_KEY
  database:
    password: ref+passbolt://b94f5947-62fd-40d3-8afd-1eadae695fbb#/custom_fields/CNPG_PASSWORD

persistence:
  enabled: true
  storageClass: zfs-vm-pool-dynamic
  size: 1Gi

image:
  repository: sissbruecker/linkding
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 9090

ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-ca
  hosts:
    - host: linkding.ref+envsubst://$LOCAL_DOMAIN_NAME
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - linkding.ref+envsubst://$LOCAL_DOMAIN_NAME
      secretName: linkding-mkcert-tls
