---
apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-grafana-admin
  namespace: monitoring
type: Opaque
stringData:
  username: ref+scw:///homelab/grafana#/admin-username
  password: ref+scw:///homelab/grafana#/admin-password
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-cnpg-credentials
  namespace: monitoring
type: Opaque
stringData:
  GF_DATABASE_PASSWORD: ref+scw:///homelab/cnpg#/grafana-password
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-influxdb-datasource
  namespace: monitoring
  labels:
    grafana_datasource: '1'
type: Opaque
stringData:
  influxdb.yaml: |-
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        access: proxy
        url: http://peanut-influxdb.peanut.svc.cluster.local:8086
        jsonData:
          version: Flux
          organization: homelab
          defaultBucket: peanut
        secureJsonData:
          token: ref+scw:///homelab/peanut-influxdb#/token
