---
apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-grafana-admin
  namespace: monitoring
type: Opaque
stringData:
  username: ref+scw:///homelab/grafana#/admin-username
  password: ref+scw:///homelab/grafana#/admin-password
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-cnpg-credentials
  namespace: monitoring
type: Opaque
stringData:
  GF_DATABASE_PASSWORD: ref+scw:///homelab/cnpg#/grafana-password
