---
apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-grafana-admin
  namespace: monitoring
type: Opaque
stringData:
  username: ref+envsubst://$KUBE_PROMETHEUS_STACK_GRAFANA_ADMIN_USERNAME
  password: ref+envsubst://$KUBE_PROMETHEUS_STACK_GRAFANA_ADMIN_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-cnpg-credentials
  namespace: monitoring
type: Opaque
stringData:
  GF_DATABASE_PASSWORD: ref+envsubst://$CLOUDNATIVE_PG_GRAFANA_PASSWORD
