---
apiVersion: v1
kind: Service
metadata:
  name: gluetun-api
  namespace: qbittorrent-vpn
spec:
  selector:
    app.kubernetes.io/name: qbittorrent-vpn
  ports:
    - name: http
      port: 8000
      targetPort: 8000
