---
apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-vpn-proton
  namespace: qbittorrent-vpn
type: Opaque
stringData:
  username: ref+envsubst://$QBITTORRENT_USERNAME
  password: ref+envsubst://$QBITTORRENT_PASSWORD
