---
apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-vpn-proton
  namespace: qbittorrent-vpn
type: Opaque
stringData:
  username: ref+passbolt://ddd2aa51-524e-411e-ad5f-aabe559471e0#/custom_fields/OPENVPN_USERNAME
  password: ref+passbolt://ddd2aa51-524e-411e-ad5f-aabe559471e0#/custom_fields/OPENVPN_PASSWORD
