---
releases:
  - name: openchamber
    namespace: openchamber
    createNamespace: true
    chart: ./charts/openchamber
    values:
      - values.yaml
    hooks:
      - events:
          - presync
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - docker build -t homelab/openchamber:latest . && docker save homelab/openchamber:latest | sudo
            ctr -n k8s.io images import -
      - events:
          - presync
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - mkdir -p $HOME_DIR/projects $HOME_DIR/worktrees
      - events:
          - presync
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - vals eval -f manifests/pv.yaml | kubectl apply -f -
