---
env:
  TZ: Europe/Paris

image:
  repository: ghcr.io/haveagitgat/tdarr
  tag: latest
node:
  enabled: true
  id: node
  image:
    repository: haveagitgat/tdarr_node
    tag: latest

persistence:
  config:
    enabled: true
    type: pvc
    mountPath: /config
    readOnly: false
    storageClass: zfs-configs-clusters-k3s-dynamic
    size: 1Gi
  data:
    enabled: true
    type: pvc
    mountPath: /server
    readOnly: false
    storageClass: zfs-configs-clusters-k3s-dynamic
    accessMode: ReadWriteOnce
    size: 5Gi
  media:
    enabled: true
    type: pvc
    mountPath: /media
    readOnly: false
    existingClaim: media-library

# podSecurityContext:
#   runAsUser: 1000
#   runAsGroup: 1000
#   fsGroup: 1000

resources:
  requests:
    cpu: 25m
    memory: 192Mi
  limits:
    cpu: '2'
    memory: 1Gi

ingress:
  main:
    enabled: true
    primary: true
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: mkcert-ca
    labels: {}
    ingressClassName: traefik
    hosts:
      - host: tdarr.ref+envsubst://$LOCAL_DOMAIN_NAME
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - tdarr.ref+envsubst://$LOCAL_DOMAIN_NAME
        secretName: tdarr-mkcert-tls
