---
apiVersion: v1
kind: Secret
metadata:
  name: warden-db-url
  namespace: warden
type: Opaque
stringData:
  db-url: postgres://warden:ref+scw:///homelab/cnpg#/warden-password+@cnpg-cluster0-rw.cnpg-clusters.svc.cluster.local:5432/warden
