---
image:
  repository: ghcr.io/druggeri/nut_exporter
  tag: 3.2.3

nut:
  server: ref+envsubst://$SINGLE_NODE_NAME
  port: 3493
  username: ''
  password: ''
  varsEnable: ''
  upsName: UPS-1

serviceMonitor:
  enabled: true
  interval: 60s
  scrapeTimeout: 10s
  release: monitoring

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
