---
apiVersion: v1
kind: Secret
metadata:
  name: rustfs-credentials
  namespace: rustfs
type: Opaque
stringData:
  RUSTFS_ACCESS_KEY: ref+scw:///homelab/rustfs#/user
  RUSTFS_SECRET_KEY: ref+scw:///homelab/rustfs#/password
