---
apiVersion: v1
kind: Secret
metadata:
  name: rustfs-credentials
  namespace: rustfs
type: Opaque
stringData:
  RUSTFS_ACCESS_KEY: ref+envsubst://$RUSTFS_ROOT_USER
  RUSTFS_SECRET_KEY: ref+envsubst://$RUSTFS_ROOT_PASSWORD
