---
replicaCount: 1

openchamber:
  image:
    repository: homelab/openchamber
    pullPolicy: Never
    tag: latest
  port: 3000

config-json: |
  {
    "$schema": "https://opencode.ai/config.json",
    "plugin": []
  }

persistence:
  workdir:
    storageClass: sc-openchamber-workdir
    accessMode: ReadWriteOnce
    size: 100Gi
  worktree:
    storageClass: sc-openchamber-worktree
    accessMode: ReadWriteOnce
    size: 10Gi
  config:
    storageClass: zfs-vm-pool-dynamic
    accessMode: ReadWriteOnce
    size: 1Gi

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts: []
  tls: []

resources:
  openchamber: {}

podSecurityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}

env: {}
