---
releases:
  - name: medialyze
    namespace: medialyze
    createNamespace: true
    chart: ./charts/medialyze
    values:
      - values.yaml
    hooks:
      - events:
          - presync
        showlogs: true
        command: /bin/sh
        args:
          - -c
          - kubectl apply -f manifests/media-pv.yaml
