---
image:
  tag: 0.2.2

persistence:
  config:
    enabled: true
    storageClass: zfs-vm-pool-dynamic
    accessMode: ReadWriteOnce
    size: 1Gi
  media:
    enabled: true
    existingClaim: media-library

ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-ca
  hosts:
    - host: medialyze.ref+envsubst://$LOCAL_DOMAIN_NAME
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - medialyze.ref+envsubst://$LOCAL_DOMAIN_NAME
      secretName: medialyze-mkcert-tls

podSecurityContext:
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

resources:
  requests:
    cpu: 5m
    memory: 32Mi
  limits:
    memory: 512Mi
