repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: prometheus
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/prometheus
    version: 25.0.0
    values:
      - values/prometheus.yaml

  - name: grafana
    namespace: monitoring
    createNamespace: true
    chart: grafana/grafana
    values:
      - values/grafana.yaml

